name: 'financial_fraud_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  financial_fraud_analytics:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    marts:
      +materialized: table
      +schema: marts
