id: fraud_pipeline
namespace: financial_fraud_analytics

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 6 * * *"

tasks:

  # STEP 1: Download multiple dataset parts (simulate large batch ingestion)
  - id: download_dataset
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - mkdir -p /tmp/fraud
      - |
        for i in {1..5}; do
          wget -O /tmp/fraud/fraud_dataset_part$i.csv \
          "https://huggingface.co/datasets/CiferAI/Cifer-Fraud-Detection-Dataset-AF/resolve/main/fraud_dataset_part$i.csv";
        done

  # STEP 2: Upload all files to GCS (Data Lake)
  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: /tmp/fraud/
    to: gs://fraud-data-lake-spatial-rig-493920-b5/raw/

  # STEP 3: Load batch files into BigQuery (partitioned + clustered)
  - id: load_to_bigquery
    type: io.kestra.plugin.gcp.bigquery.Load
    from: gs://fraud-data-lake-spatial-rig-493920-b5/raw/*.csv
    destinationTable: spatial-rig-493920-b5.fraud_dataset.transactions_raw
    format: CSV
    autodetect: true
    writeDisposition: WRITE_TRUNCATE

    # ✅ Partition + cluster (for full marks)
    timePartitioning:
      type: DAY
      field: step

    clustering:
      fields: ["type"]

  # STEP 4: Run dbt transformations (staging → intermediate → marts)
  - id: run_dbt
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - cd ~/financial-fraud-analytics-pipeline/dbt
      - dbt run

  # STEP 5: Optional tests (extra credibility)
  - id: run_dbt_tests
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - cd ~/financial-fraud-analytics-pipeline/dbt
      - dbt test

  # STEP 6: Final log (observability)
  - id: pipeline_complete
    type: io.kestra.core.tasks.log.Log
    message: "Fraud analytics pipeline executed successfully"